# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 'latest'
  imageName: 'shashankadepu/eureka-server'

stages:
- stage: Build
  displayName: Build and Push Docker image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - script: |
        echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
      displayName: Docker Hub Login
    - task: Docker@2
      displayName: Build and Push Docker image
      inputs:
        command: buildAndPush
        dockerfile: '**/Dockerfile'
        repository: 
        tags: |
          $(tag)
